export const Authors = [
    {
        key: 1,
        bookImage: '/images/book1.png',
        title: 'The Last War',
        author: 'Mickalene Thomas',
        price: '0.05RTH',
    },
    {
        key: 2,
        bookImage: '/images/book2.png',
        title: 'Black American Portraits',
        author: 'Stevie Wonder',
        price: '0.05RTH',
    },
    {
        key: 3,
        bookImage: '/images/book3.png',
        title: 'Draw What You See',
        author: 'Kathleen benson',
        price: '0.05RTH',
    },
    {
        key: 4,
        bookImage: '/images/book4.png',
        title: 'Oxford History of Art',
        author: 'Sharon F. Patton',
        price: '0.05RTH',
    },
    {
        key: 5,
        bookImage: '/images/book2.png',
        title: 'The Last War',
        author: 'Mickalene Thomas',
        price: '0.05RTH',
    },
    {
        key: 6,
        bookImage: '/images/book1.png',
        title: 'The Last War',
        author: 'Mickalene Thomas',
        price: '0.05RTH',
    },
    {
        key: 7,
        bookImage: '/images/book2.png',
        title: 'The Last War',
        author: 'Mickalene Thomas',
        price: '0.05RTH',
    },
    {
        key: 8,
        bookImage: '/images/book3.png',
        title: 'The Last War',
        author: 'Mickalene Thomas',
        price: '0.05RTH',
    },
    {
        key: 9,
        bookImage: '/images/book4.png',
        title: 'The Last War',
        author: 'Mickalene Thomas',
        price: '0.05RTH',
    },
    {
        key: 10,
        bookImage: '/images/book3.png',
        title: 'The Last War',
        author: 'Mickalene Thomas',
        price: '0.05RTH',
    },
    {
        key: 11,
        bookImage: '/images/book4.png',
        title: 'The Last War',
        author: 'Mickalene Thomas',
        price: '0.05RTH',
    },
]